# Generated by Django 3.1.3 on 2020-11-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_int',
            field=models.IntegerField(default=0),
        ),
    ]
