# Generated by Django 3.1.3 on 2020-11-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_district_district_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_text',
        ),
    ]
