# Generated by Django 3.1.3 on 2020-11-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_remove_district_district_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_int',
            new_name='district_num',
        ),
        migrations.AddField(
            model_name='ballottext',
            name='district_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district_num',
            field=models.IntegerField(default=0),
        ),
    ]
