# Generated by Django 3.1.3 on 2020-11-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20201130_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballottext',
            name='ballot_cat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ballot_cat',
            field=models.IntegerField(default=0),
        ),
    ]
